FROM node:18-alpine

WORKDIR /app

# nur deps installieren
COPY package*.json ./
RUN npm ci --only=production

# Rest rüberkopieren
COPY src ./src
COPY src/admin-ui ./admin-ui

EXPOSE 3001

CMD ["node", "src/admin-server.js"]